### ISSUE TITLE
RT#21230 installing on Mac OS X 10.4

### ISSUE THREAD

**Issue by duffee** [duffee/Boost-Graph#7]
Wed, 30 Aug 2006 00:49:26 -0400 (EDT)
-
From: | Lisa Friedland <lfriedl@cs.umass.edu>

My installation seems to be working fine now (and I'm looking forward to 
using it for its connectedComponents() function), but I had some 
difficulties getting it there.  I'm running Mac OS X 10.4.

1) We don't have sys/vfs.h, required in Directed/Directed.c and 
Undirected/Undirected.c, so this caused compile errors.  Following 
instructions found on the web somewhere, I replaced these with 
sys/mount.h.

2) Error which was reported last month in the forum:
../include/BoostGraph_undirected_i.h: In member function `virtual 
std::vector<int, std::allocator<i +nt> > 
BoostGraph_undirected_i<G>::connectedComponents()': 
../include/BoostGraph_undirected_i.h:59: error: `_changed' was not 
declared in this scope

Fixed (through sheer luck trying this randomly) by changing the offending 
line 59 to refer to the field explicitly:
if (this->_changed!=0) this->_fillGraph();

Maybe different g++ versions do strange things?  I have gcc version 4.0.1.

3) When I went to run the tests, they failed because I didn't have 
Class::AutoClass on my system (which I then installed from CPAN), then 
because I didn't have Bio::ISB::POS::Interactable (which cannot be 
obtained from CPAN).  These dependencies are something to think about. 
(I.e. maybe the Bio one could be gotten rid of, and the AutoClass one 
automatically installed before this package.)

I hope these can be changed in the next version!
-Lisa

**Comment by duffee** [comment]
Hi @lfriedl

I've got some spare cycles and I'm getting the [Boost::Graph](https://metacpan.org/pod/Boost::Graph) Perl module into a working state (working on the v1.5 branch). I no longer have a Mac, but it now is working on Boost 1.91

I'm not the author. I ended up as the maintainer because somewhere around 2009 I needed the module for my thesis. A bunch of helpful gurus fixed the bugs, but left me holding the module.

Installing might be as easy as
```
brew install boost
cpanm Boost::Graph
```
